spring:
  data:
    mongodb:
      database:
      uri:

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            redirectUri:
            scope:
              - email
              - profile
          facebook:
            clientId:
            clientSecret:
            redirectUri:
            scope:
              - email
              - public_profile
          github:
            clientId:
            clientSecret:
            redirectUri:
            scope:
              - user:email
              - read:user
        provider:
          facebook:
            authorizationUri:
            tokenUri:
            userInfoUri:


server:
  port:
  application:
    name:

app:
  auth:
    tokenSecret:
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080,http://localhost:8102
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - http://localhost:8102/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect